#!/bin/sh
#

while read line; do
    # Skip comments
    if [ "${line:0:1}" == "#" ]; then
        continue
    fi
    if [ ${#line} -le 20 ]; then
        echo "Please enter a message with at least 20 characters."
        echo "The following commit message has only ${#line} characters."
        echo "Message: ${line}"
        exit 1
    fi
done < "${1}"

exit 0